// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pjrafogbhuttkbrufdaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcmFmb2diaHV0dGticnVmZGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMTI5ODMsImV4cCI6MjA4ODU4ODk4M30.IN113hERRG8lHbWlzThgQL2vuex4PrLqcD3lQnPBeqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);